<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="sample_MSET" targetNamespace="somenamespace" xmlns:oldtns1="http://www.mrmnames.net" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="somenamespace" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="sample_MSETSOAP_HTTP_Binding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema targetNamespace="somenamespace" xmlns:mrm="somenamespace">
      <xsd:import namespace="http://www.mrmnames.net" schemaLocation="../net/mrmnames/www/sample_msgdef.mxsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="Operation1_in">
    <wsdl:part element="oldtns1:request" name="request"/>
  </wsdl:message>
  <wsdl:message name="Operation1_out">
    <wsdl:part element="oldtns1:response" name="response"/>
  </wsdl:message>
  <wsdl:portType name="sample_MSETPortType">
    <wsdl:operation name="Operation1">
      <wsdl:input message="tns:Operation1_in" name="Operation1_Input"/>
      <wsdl:output message="tns:Operation1_out" name="Operation1_Output"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="sample_MSETSOAP_HTTP_Binding" type="tns:sample_MSETPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Operation1">
      <soap:operation soapAction=""/>
      <wsdl:input name="Operation1_Input">
        <soap:body parts="request" use="literal"/>
      </wsdl:input>
      <wsdl:output name="Operation1_Output">
        <soap:body parts="response" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="sample_MSETSOAP_HTTP_Service">
    <wsdl:port binding="tns:sample_MSETSOAP_HTTP_Binding" name="sample_MSETSOAP_HTTP_Port">
      <soap:address location="http://localhost:7800/sampleTest"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>